### ISSUE TITLE
Example for call with params

### ISSUE THREAD

**Issue by benjaminmbrown** [Horyus/vortex#18]
Hi @mortimr ,

Cool project!

Not a react expert (yet) so I'm digging through this. Can you provide an example of how to call a smart contract function like this from the front end of vortex:

```
function initiateBounty(uint _bountyId) public returns(bool)
{
        require(
            bounties[_bountyId].taken == false && 
            bounties[_bountyId].complete == false);

        bounties[_bountyId].taker = msg.sender;
        bounties[_bountyId].taken = true;

        emit BountyTaken(msg.sender, _bountyId);
        return true;
    }

````

**Comment by mortimr** [comment]
Hi @benjaminmbrown,

Thanks for the support.

If I understand correctly, you want to call a state modifying method from Vortex properly ?
This is how the contract object is organized:

```js
{
...
    instance: {
    ...
        vortexMethods: {
            // Here you will find all your contract methods
        }
    ...
    }
...
}
```

You can have a look at [this line](https://github.com/Horyus/vortex-demo-truffle/blob/a4696c23200b72750e4f362e00e0f0b3687b8d19/src/demo-sections/list-contracts/index.js#L57) from the demo app where I edit the value stored by the `SimpleStorage` smart contract.

This is [another example](https://github.com/Horyus/ticket721-webapp/blob/055af52d2e7533e6322cc5c1319ebd28758191cd/src/components/ticket_showcase/index.js#L102-L103) where I call a constant method.

This [file](https://github.com/Horyus/vortex/blob/develop/_sources/sources/propMappers.ts) contains methods you can use in your `mapStateToProps` functions. They will help you recover contract instances, call methods, get IPFS data, get Events ...

Constant and State Modifying methods are handled a bit differently. 
- Constant methods work around data caching so you don't have to fetch the same data multiple times and if it hasn't really changed on the blockchain.
- State Modifying methods are juste like transactions. When called, a new transaction is added in the store and you can follow its status directly (live verification count etc)

**Comment by benjaminmbrown** [comment]
Awesome, thank you for the help
